### ISSUE TITLE
Conversion error: `unknown property '0' among [foo];`

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-terraform-bridge#1145]
Error converting https://github.com/terraform-aws-modules/terraform-aws-eks:

```
$ pulumi convert --from terraform --language typescript --out pulumi
error: main.pp:54,41-44: unknown property '0' among [endpointPublicAccess publicAccessCidrs securityGroupIds subnetIds vpcId clusterSecurityGroupId endpointPrivateAccess];
error: node_groups.pp:35,75-78: unknown property '0' among [data];
error: node_groups.pp:294,219-222: unknown property '0' among [endpointPrivateAccess endpointPublicAccess publicAccessCidrs securityGroupIds subnetIds vpcId clusterSecurityGroupId];
error: node_groups.pp:399,220-223: unknown property '0' among [publicAccessCidrs securityGroupIds subnetIds vpcId clusterSecurityGroupId endpointPrivateAccess endpointPublicAccess];
```

Errors converting https://github.com/aws-samples/hub-and-spoke-with-inspection-vpc-terraform:

```
$ pulumi convert --from terraform --language typescript --out pulumi
error: main.pp:82,20-24: unknown property 'key' among [value];
error: main.pp:125,20-24: unknown property 'key' among [value];
```

**Comment by justinvp** [comment]
A user was trying to convert https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/multi-tenancy-with-teams to typescript and got similar errors:

```
error: main.pp:25,36-42: unknown property 'vpcId' among [redshiftSubnetArns vpcIpv6AssociationId redshiftNetworkAclId intraRouteTableAssociationIds cgwIds defaultVpcMainRouteTableId databaseNetworkAclArn elasticacheNetworkAclId publicSubnetsOutput vpcSecondaryCidrBlocks igwArn redshiftRouteTableAssociationIds intraNetworkAclId defaultVpcDefaultNetworkAclId vpcFlowLogId elasticacheRouteTableAssociationIds intraSubnetsCidrBlocks redshiftNetworkAclArn intraSubnetArns defaultNetworkAclId privateSubnetArns privateSubnetsOutput outpostNetworkAclId vpcEnableDnsSupport igwId intraNetworkAclArn defaultVpcCidrBlock vpcIdOutput publicNetworkAclArn natPublicIps nameOutput databaseSubnetsOutput vgwArn vpcMainRouteTableId privateNetworkAclId defaultSecurityGroupId elasticacheSubnetArns databaseRouteTableIds databaseInternetGatewayRouteId intraSubnetsOutput elasticacheSubnetGroupNameOutput vpcArn publicSubnetsCidrBlocks redshiftSubnetGroup defaultVpcInstanceTenancy publicInternetGatewayIpv6RouteId elasticacheSubnetsIpv6CidrBlocks vpcIpv6CidrBlock outpostNetworkAclArn publicNetworkAclId privateNatGatewayRouteIds outpostSubnetsIpv6CidrBlocks cgwArns vgwId publicSubnetArns publicInternetGatewayRouteId privateNetworkAclArn databaseSubnetsCidrBlocks databaseSubnetGroup intraRouteTableIds egressOnlyInternetGatewayId thisCustomerGateway vpcInstanceTenancy privateRouteTableAssociationIds redshiftSubnetsIpv6CidrBlocks redshiftPublicRouteTableAssociationIds databaseSubnetArns databaseIpv6EgressRouteId elasticacheNetworkAclArn natIds publicRouteTableIdsOutput publicRouteTableAssociationIds databaseRouteTableAssociationIds vpcFlowLogDestinationArn vpcEnableDnsHostnames databaseSubnetGroupNameOutput redshiftSubnetsOutput elasticacheSubnetsOutput defaultVpcDefaultRouteTableId vpcFlowLogCloudwatchIamRoleArn privateSubnetsCidrBlocks redshiftSubnetsCidrBlocks natgwIds defaultVpcEnableDnsSupportOutput privateIpv6EgressRouteIds outpostSubnetsOutput databaseNetworkAclId defaultVpcId defaultVpcArn azsOutput defaultRouteTableId dhcpOptionsId redshiftRouteTableIdsOutput elasticacheSubnetsCidrBlocks defaultVpcEnableDnsHostnamesOutput vpcFlowLogDestinationType vpcCidrBlock privateSubnetsIpv6CidrBlocks elasticacheSubnetGroup vpcOwnerId outpostSubnetsCidrBlocks publicSubnetsIpv6CidrBlocks privateRouteTableIdsOutput databaseNatGatewayRouteIds defaultVpcDefaultSecurityGroupId databaseSubnetsIpv6CidrBlocks elasticacheRouteTableIds intraSubnetsIpv6CidrBlocks outpostSubnetArns];
error: main.pp:26,36-51: unknown property 'privateSubnets' among [redshiftRouteTableAssociationIds intraNetworkAclId elasticacheRouteTableAssociationIds intraSubnetsCidrBlocks defaultVpcDefaultNetworkAclId vpcFlowLogId defaultNetworkAclId privateSubnetArns redshiftNetworkAclArn intraSubnetArns vpcEnableDnsSupport igwId privateSubnetsOutput outpostNetworkAclId vpcIdOutput publicNetworkAclArn intraNetworkAclArn defaultVpcCidrBlock natPublicIps nameOutput vpcMainRouteTableId privateNetworkAclId databaseSubnetsOutput vgwArn defaultSecurityGroupId elasticacheSubnetArns intraSubnetsOutput databaseRouteTableIds databaseInternetGatewayRouteId elasticacheSubnetGroupNameOutput vpcArn publicSubnetsCidrBlocks defaultVpcInstanceTenancy publicInternetGatewayIpv6RouteId redshiftSubnetGroup vpcIpv6CidrBlock outpostNetworkAclArn elasticacheSubnetsIpv6CidrBlocks publicNetworkAclId vgwId publicSubnetArns publicInternetGatewayRouteId privateNatGatewayRouteIds outpostSubnetsIpv6CidrBlocks cgwArns intraRouteTableIds egressOnlyInternetGatewayId thisCustomerGateway vpcInstanceTenancy privateRouteTableAssociationIds privateNetworkAclArn databaseSubnetsCidrBlocks databaseSubnetGroup databaseSubnetArns databaseIpv6EgressRouteId redshiftSubnetsIpv6CidrBlocks redshiftPublicRouteTableAssociationIds publicRouteTableIdsOutput publicRouteTableAssociationIds elasticacheNetworkAclArn natIds vpcEnableDnsHostnames databaseSubnetGroupNameOutput databaseRouteTableAssociationIds vpcFlowLogDestinationArn elasticacheSubnetsOutput defaultVpcDefaultRouteTableId redshiftSubnetsOutput privateSubnetsCidrBlocks redshiftSubnetsCidrBlocks vpcFlowLogCloudwatchIamRoleArn privateIpv6EgressRouteIds outpostSubnetsOutput natgwIds defaultVpcEnableDnsSupportOutput azsOutput defaultRouteTableId dhcpOptionsId databaseNetworkAclId defaultVpcId defaultVpcArn vpcFlowLogDestinationType vpcCidrBlock privateSubnetsIpv6CidrBlocks redshiftRouteTableIdsOutput elasticacheSubnetsCidrBlocks defaultVpcEnableDnsHostnamesOutput vpcOwnerId outpostSubnetsCidrBlocks elasticacheSubnetGroup defaultVpcDefaultSecurityGroupId publicSubnetsIpv6CidrBlocks privateRouteTableIdsOutput databaseNatGatewayRouteIds intraSubnetsIpv6CidrBlocks outpostSubnetArns databaseSubnetsIpv6CidrBlocks elasticacheRouteTableIds redshiftSubnetArns vpcIpv6AssociationId redshiftNetworkAclId databaseNetworkAclArn elasticacheNetworkAclId intraRouteTableAssociationIds cgwIds defaultVpcMainRouteTableId vpcSecondaryCidrBlocks igwArn publicSubnetsOutput];
error: main.pp:21,1-39,2: main.pp:54,41-44: unknown property '0' among [clusterSecurityGroupId endpointPrivateAccess endpointPublicAccess publicAccessCidrs securityGroupIds subnetIds vpcId]; , and 9 other diagnostic(s); main.pp:54,41-44: unknown property '0' among [clusterSecurityGroupId endpointPrivateAccess endpointPublicAccess publicAccessCidrs securityGroupIds subnetIds vpcId]; , and 9 other diagnostic(s)
```

**Comment by Zaid-Ajaj** [comment]
After meticulous digging into the program and debugging it, I managed to isolate the issue and find the root cause. 

The problem is in this resource declaration:
```tf
resource "aws_ec2_tag" "cluster_primary_security_group" {
  # This should not affect the name of the cluster primary security group
  # Ref: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2006
  # Ref: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2008
  for_each = { for k, v in merge(var.tags, var.cluster_tags) :
    k => v if local.create && k != "Name" && var.create_cluster_primary_security_group_tags && v != null
  }

  resource_id = aws_eks_cluster.this[0].vpc_config[0].cluster_security_group_id
  key         = each.key
  value       = each.value
}
``` 
specifically the expression:
```
aws_eks_cluster.this[0].vpc_config[0].cluster_security_group_id
```
should actually be
```
aws_eks_cluster.this[0].vpc_config.cluster_security_group_id
```
Notice how the index zero should not be there. 

This is another edge case for `MaxItemsOne` where we should actually _remove_ the extra index`[0]` when we detect that the property has an `MaxItemsOne` override.

**Comment by Zaid-Ajaj** [comment]
Should be resolved by #1182 but needs double checking

**Comment by justinvp** [comment]
@Zaid-Ajaj from our previous discussions, I'm guessing the following two cases are different and need their own issues.

I'm actually seeing the latter case a bunch trying to convert individual examples from https://github.com/terraform-aws-modules/terraform-aws-vpc/tree/master/examples:

## Case 1

Errors converting https://github.com/aws-samples/hub-and-spoke-with-inspection-vpc-terraform:

```
$ pulumi convert --from terraform --language typescript --out pulumi
error: main.pp:82,20-24: unknown property 'key' among [value];
error: main.pp:125,20-24: unknown property 'key' among [value];
```

## Case 2

A user was trying to convert https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/multi-tenancy-with-teams to typescript and got similar errors:

```
error: main.pp:25,36-42: unknown property 'vpcId' among [redshiftSubnetArns vpcIpv6AssociationId redshiftNetworkAclId intraRouteTableAssociationIds cgwIds defaultVpcMainRouteTableId databaseNetworkAclArn elasticacheNetworkAclId publicSubnetsOutput vpcSecondaryCidrBlocks igwArn redshiftRouteTableAssociationIds intraNetworkAclId defaultVpcDefaultNetworkAclId vpcFlowLogId elasticacheRouteTableAssociationIds intraSubnetsCidrBlocks redshiftNetworkAclArn intraSubnetArns defaultNetworkAclId privateSubnetArns privateSubnetsOutput outpostNetworkAclId vpcEnableDnsSupport igwId intraNetworkAclArn defaultVpcCidrBlock vpcIdOutput publicNetworkAclArn natPublicIps nameOutput databaseSubnetsOutput vgwArn vpcMainRouteTableId privateNetworkAclId defaultSecurityGroupId elasticacheSubnetArns databaseRouteTableIds databaseInternetGatewayRouteId intraSubnetsOutput elasticacheSubnetGroupNameOutput vpcArn publicSubnetsCidrBlocks redshiftSubnetGroup defaultVpcInstanceTenancy publicInternetGatewayIpv6RouteId elasticacheSubnetsIpv6CidrBlocks vpcIpv6CidrBlock outpostNetworkAclArn publicNetworkAclId privateNatGatewayRouteIds outpostSubnetsIpv6CidrBlocks cgwArns vgwId publicSubnetArns publicInternetGatewayRouteId privateNetworkAclArn databaseSubnetsCidrBlocks databaseSubnetGroup intraRouteTableIds egressOnlyInternetGatewayId thisCustomerGateway vpcInstanceTenancy privateRouteTableAssociationIds redshiftSubnetsIpv6CidrBlocks redshiftPublicRouteTableAssociationIds databaseSubnetArns databaseIpv6EgressRouteId elasticacheNetworkAclArn natIds publicRouteTableIdsOutput publicRouteTableAssociationIds databaseRouteTableAssociationIds vpcFlowLogDestinationArn vpcEnableDnsHostnames databaseSubnetGroupNameOutput redshiftSubnetsOutput elasticacheSubnetsOutput defaultVpcDefaultRouteTableId vpcFlowLogCloudwatchIamRoleArn privateSubnetsCidrBlocks redshiftSubnetsCidrBlocks natgwIds defaultVpcEnableDnsSupportOutput privateIpv6EgressRouteIds outpostSubnetsOutput databaseNetworkAclId defaultVpcId defaultVpcArn azsOutput defaultRouteTableId dhcpOptionsId redshiftRouteTableIdsOutput elasticacheSubnetsCidrBlocks defaultVpcEnableDnsHostnamesOutput vpcFlowLogDestinationType vpcCidrBlock privateSubnetsIpv6CidrBlocks elasticacheSubnetGroup vpcOwnerId outpostSubnetsCidrBlocks publicSubnetsIpv6CidrBlocks privateRouteTableIdsOutput databaseNatGatewayRouteIds defaultVpcDefaultSecurityGroupId databaseSubnetsIpv6CidrBlocks elasticacheRouteTableIds intraSubnetsIpv6CidrBlocks outpostSubnetArns];
error: main.pp:26,36-51: unknown property 'privateSubnets' among [redshiftRouteTableAssociationIds intraNetworkAclId elasticacheRouteTableAssociationIds intraSubnetsCidrBlocks defaultVpcDefaultNetworkAclId vpcFlowLogId defaultNetworkAclId privateSubnetArns redshiftNetworkAclArn intraSubnetArns vpcEnableDnsSupport igwId privateSubnetsOutput outpostNetworkAclId vpcIdOutput publicNetworkAclArn intraNetworkAclArn defaultVpcCidrBlock natPublicIps nameOutput vpcMainRouteTableId privateNetworkAclId databaseSubnetsOutput vgwArn defaultSecurityGroupId elasticacheSubnetArns intraSubnetsOutput databaseRouteTableIds databaseInternetGatewayRouteId elasticacheSubnetGroupNameOutput vpcArn publicSubnetsCidrBlocks defaultVpcInstanceTenancy publicInternetGatewayIpv6RouteId redshiftSubnetGroup vpcIpv6CidrBlock outpostNetworkAclArn elasticacheSubnetsIpv6CidrBlocks publicNetworkAclId vgwId publicSubnetArns publicInternetGatewayRouteId privateNatGatewayRouteIds outpostSubnetsIpv6CidrBlocks cgwArns intraRouteTableIds egressOnlyInternetGatewayId thisCustomerGateway vpcInstanceTenancy privateRouteTableAssociationIds privateNetworkAclArn databaseSubnetsCidrBlocks databaseSubnetGroup databaseSubnetArns databaseIpv6EgressRouteId redshiftSubnetsIpv6CidrBlocks redshiftPublicRouteTableAssociationIds publicRouteTableIdsOutput publicRouteTableAssociationIds elasticacheNetworkAclArn natIds vpcEnableDnsHostnames databaseSubnetGroupNameOutput databaseRouteTableAssociationIds vpcFlowLogDestinationArn elasticacheSubnetsOutput defaultVpcDefaultRouteTableId redshiftSubnetsOutput privateSubnetsCidrBlocks redshiftSubnetsCidrBlocks vpcFlowLogCloudwatchIamRoleArn privateIpv6EgressRouteIds outpostSubnetsOutput natgwIds defaultVpcEnableDnsSupportOutput azsOutput defaultRouteTableId dhcpOptionsId databaseNetworkAclId defaultVpcId defaultVpcArn vpcFlowLogDestinationType vpcCidrBlock privateSubnetsIpv6CidrBlocks redshiftRouteTableIdsOutput elasticacheSubnetsCidrBlocks defaultVpcEnableDnsHostnamesOutput vpcOwnerId outpostSubnetsCidrBlocks elasticacheSubnetGroup defaultVpcDefaultSecurityGroupId publicSubnetsIpv6CidrBlocks privateRouteTableIdsOutput databaseNatGatewayRouteIds intraSubnetsIpv6CidrBlocks outpostSubnetArns databaseSubnetsIpv6CidrBlocks elasticacheRouteTableIds redshiftSubnetArns vpcIpv6AssociationId redshiftNetworkAclId databaseNetworkAclArn elasticacheNetworkAclId intraRouteTableAssociationIds cgwIds defaultVpcMainRouteTableId vpcSecondaryCidrBlocks igwArn publicSubnetsOutput];
```

Converting https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/examples/iam-assumable-role to TS:

```
pulumi convert --from terraform --language typescript --out pulumi
error: outputs.pp:13,32-48: unknown property 'roleRequiresMfa' among [roleRequiresMfaOutput iamInstanceProfileName iamInstanceProfileId iamRolePath iamRoleName iamRoleUniqueId iamInstanceProfileArn iamInstanceProfilePath roleStsExternalidOutput iamRoleArn];
```

Converting https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/examples/iam-github-oidc to C#:

```
pulumi convert --from terraform --language c# --out pulumi
error: outputs.pp:8,32-36: unknown property 'url' among [urlOutput arn];
error: outputs.pp:18,28-33: unknown property 'name' among [pathOutput uniqueId arn nameOutput];
error: outputs.pp:21,28-33: unknown property 'path' among [nameOutput pathOutput uniqueId arn];
```

**Comment by justinvp** [comment]
Opened separate issues for these:
- Case 1: https://github.com/pulumi/pulumi-terraform-bridge/issues/1184
- Case 2: https://github.com/pulumi/pulumi-terraform-bridge/issues/1183

Case2 (https://github.com/pulumi/pulumi-terraform-bridge/issues/1183) is being hit way more, so higher priority

**Comment by justinvp** [comment]
@Zaid-Ajaj, I'm still seeing `unknown property '0' among [foo];` with the latest bits. Converting https://github.com/philips-labs/terraform-aws-github-runner to Python (or TS):

```
pulumi convert --from terraform --language python --out pulumi
Converting from terraform...
Converting to python...
error: main.pp:161,25-28: unknown property '0' among [bucket runnerDistributionObjectKey lambda lambdaLogGroup lambdaRole];
error: main.pp:162,25-28: unknown property '0' among [bucket runnerDistributionObjectKey lambda lambdaLogGroup lambdaRole];
error: main.pp:163,25-28: unknown property '0' among [lambda lambdaLogGroup lambdaRole bucket runnerDistributionObjectKey];
error: main.pp:147,1-237,2: /var/folders/xg/z6dhmklj23540z44cm7sgkcr0000gn/T/pulumi-convert657194420/modules/runners/pool.pp:0,0-55,2: /var/folders/xg/z6dhmklj23540z44cm7sgkcr0000gn/T/pulumi-convert657194420/modules/runners/pool/main.pp:84,20-43: the first argument to 'length' must be a list, map, object, tuple, or string; , and 5 other diagnostic(s); /var/folders/xg/z6dhmklj23540z44cm7sgkcr0000gn/T/pulumi-convert657194420/modules/runners/pool/main.pp:84,20-43: the first argument to 'length' must be a list, map, object, tuple, or string; , and 5 other diagnostic(s); /var/folders/xg/z6dhmklj23540z44cm7sgkcr0000gn/T/pulumi-convert657194420/modules/runners/pool.pp:0,0-55,2: /var/folders/xg/z6dhmklj23540z44cm7sgkcr0000gn/T/pulumi-convert657194420/modules/runners/pool/main.pp:84,20-43: the first argument to 'length' must be a list, map, object, tuple, or string; , and 5 other diagnostic(s); /var/folders/xg/z6dhmklj23540z44cm7sgkcr0000gn/T/pulumi-convert657194420/modules/runners/pool/main.pp:84,20-43: the f
irst argument to 'length' must be a list, map, object, tuple, or string; , and 5 other diagnostic(s)
error: outputs.pp:28,36-39: unknown property '0' among [lambdaRole bucket runnerDistributionObjectKey lambda lambdaLogGroup];
error: outputs.pp:29,36-39: unknown property '0' among [lambda lambdaLogGroup lambdaRole bucket runnerDistributionObjectKey];
error: outputs.pp:30,36-39: unknown property '0' among [bucket runnerDistributionObjectKey lambda lambdaLogGroup lambdaRole];
error: outputs.pp:31,44-47: unknown property '0' among [lambda lambdaLogGroup lambdaRole bucket runnerDistributionObjectKey];
error: outputs.pp:32,36-39: unknown property '0' among [bucket runnerDistributionObjectKey lambda lambdaLogGroup lambdaRole];
error: could not generate output program: failed to bind program
```

**Comment by Zaid-Ajaj** [comment]
@justinvp Using latest `pulumi-converter-terraform` v0.0.12 and latest pulumi CLI including https://github.com/pulumi/pulumi/pull/13138 I am able to convert https://github.com/philips-labs/terraform-aws-github-runner both to typescript and python without errors
