### ISSUE TITLE
The bridge does not accept secrets panic

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#2439]
### What happened?

After upgrading to the latest bridge, users encountered "The bridge does not accept secrets" panics.

### Example

https://github.com/pulumi/pulumi-gcp/issues/2405 is a good example where this was discovered.

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-hcloud/issues/603

**Comment by MehulKothari-Circuitry** [comment]
Facing similar issue with respect to deployment of my pulumi stack related to databricks.

  panic: fatal: An assertion has failed: The bridge does not accept secrets, so we should not encounter them here
    goroutine 33 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...

**Comment by VenelinMartinov** [comment]
@MehulKothari-Circuitry, thanks for reporting. Which provider are you using?

**Comment by VenelinMartinov** [comment]
Fixed in https://github.com/pulumi/pulumi-terraform-bridge/pull/2438

**Comment by MehulKothari-Circuitry** [comment]
> [@MehulKothari-Circuitry](https://github.com/MehulKothari-Circuitry), thanks for reporting. Which provider are you using?

Hey @VenelinMartinov  the provider is Databricks

**Comment by VenelinMartinov** [comment]
Ok, thanks, I'll make a databricks release which should fix this!

**Comment by MehulKothari-Circuitry** [comment]
> Ok, thanks, I'll make a databricks release which should fix this!
Did u update for databricks provider?
Hey @VenelinMartinov  can you update for pulumi, pulumi-aws provider as well?

**Comment by MehulKothari-Circuitry** [comment]
Ok, thanks, I'll make a databricks release which should fix this!
Did u update for databricks provider?
Hey @VenelinMartinov can you update for pulumi, pulumi-aws provider as well?

**Comment by t0yv0** [comment]
Releasing AWS here: https://github.com/pulumi/pulumi-aws/pull/4526#pullrequestreview-2328610244 apologies for the disruption again.

**Comment by VenelinMartinov** [comment]
Reopening until we resolve all provider issues

**Comment by sdibernardo** [comment]
I just pulled the latest versions and tried again, yet I still get the panic.

>  panic: fatal: An assertion has failed: The bridge does not accept secrets, so we should not encounter them here
    goroutine 24 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0xe0?, {0x1042078b2?, 0x140007b9230?}, {0x0?, 0x0?, 0x14000310080?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/util/contract/assert.go:35 +0xe0
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*ConfigEncoding).UnfoldProperties(0x14000310080, 0x14000f54390)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.0/pkg/tfbridge/config_encoding.go:143 +0x214
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/configencoding.(*provider[...]).ConfigureWithContext(0x14000e3b300, {0x104fbaba8?, 0x14000f54150}, 0x14000f54390)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/configencoding/provider.go:110 +0x4c
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(*provider).Configure(0x104ad1a20?, {0x104fbaba8?, 0x14000f54150?}, {0x14000f1c7c0?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/plugin/provider_context.go:143 +0x30
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.providerThunk.Configure({{0x104fe3e50?, 0x1400063aed0?}}, {0x104fbaba8, 0x14000f54150}, {0x0?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/plugin/provider_server.go:83 +0x84
    github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*providerServer).Configure(0x14000dca030, {0x104fbaba8, 0x14000f54150}, 0x14000981100)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/resource/plugin/provider_server.go:346 +0x2c4
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(*providerServer).Configure(0x104f9b020?, {0x104fbaba8?, 0x14000f54150?}, 0x0?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/plugin/provider_server.go:57 +0x30
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Configure.func1()
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:298 +0x74
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...].func1()
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:595 +0x48
    created by github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...] in goroutine 22
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:594 +0x78

My dependencies are:

> Dependencies:
NAME                  VERSION
typescript            5.6.2
@pulumi/kubernetes    4.18.1
@pulumi/openstack     4.1.3
@pulumi/pulumi        3.134.1
@pulumi/random        4.16.6
@types/node           22.7.2
@ovhcloud/pulumi-ovh  0.50.0
@pulumi/aws           6.53.0
@pulumi/azure-native  2.63.0
rollup                4.22.4
tsup                  8.3.0


I did a fresh clean + install but still I get this error and from the logs it seems that old versions are still used, e.g. v3.133.0 for the pulumi sdk. 

Any advice on how to proceed? 

Best regards
Sascha

**Comment by t0yv0** [comment]
Do you know which provider is panic'ing Sascha, there should be some more context in the output compared to what you listed? We can double-check the release of that provider.

**Comment by sdibernardo** [comment]
> Previewing update (dev):
>   Type                                             Name                         Plan     Info
>      pulumi:pulumi:Stack                 environment-dev                   26 messages
>      └─ ovh:CloudProject:User     dev-user                                1 error
> 
> Diagnostics:
>   ovh:CloudProject:User (dev-user):
>     error: error reading from server: EOF
> 
> pulumi:pulumi:Stack (environment-dev):
>     (node:23091) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
>     (Use `node --trace-deprecation ...` to show where the warning was created)
> 
>     panic: fatal: An assertion has failed: The bridge does not accept secrets, so we should not encounter them here

Seems to me like something with OVH Provider is broken, but I am not sure. 
Happy to provide more info if needed 👍

**Comment by iwahbe** [comment]
Hi @sdibernardo. pulumi-ovh is maintained by ovh, but I have opened a [PR](https://github.com/ovh/pulumi-ovh/pull/233) to fix the problem. Thanks for pointing this out.

**Comment by sdibernardo** [comment]
Thank you for taking action so quick 🥇
